[Variables]
Main_FG =00FF9C
Secondary_FG =DEDEDE
Main_BG =2E2837
Sidebar_And_Player_BG =2E2837
Cover_Overlay_And_Shadow =000000
Indicator_FG_And_Button_BG =00FF9C
Pressing_FG = FF5C86
Slider_BG =3F3C45
Sidebar_Indicator_And_Hover_Button_BG =00BF76
Scrollbar_FG_And_Selected_Row_BG =615670
Pressing_Button_FG =DEDEDE
Pressing_Button_BG =383145
Selected_Button =00BF76
Miscellaneous_BG =3F3C45
Miscellaneous_Hover_BG =383145
Preserve_1 =FFFFFF